version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sterling-backend
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - APP_URL=$APP_URL
      - APP_NAME=$APP_NAME
      - JWT_SECRET=$JWT_SECRET
      - MONGO_DB_TEST=$MONGO_DB_TEST
      - SESSION_SECRET=$SESSION_SECRET
      - REDIS_HOST=redis
      - REDIS_PORT=$REDIS_PORT
    ports:
      - '4000:3030'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon server.js

  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis-data:/var/lib/redis
      - redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
  redis-data:
  redis.conf:
